name: Publish to PyPI and conda-forge

on:
  release:
    types: [published]

jobs:
  build-and-publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build package
        run: python setup.py sdist bdist_wheel
      # - name: Upload to PyPI
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      #   run: twine upload dist/*
  
  build-and-publish-conda:
    needs: build-and-publish-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          conda-version: 'latest'
          python-version: '3.10'
      - name: Create conda environment
        run: conda create -n myenv python=3.10
      - name: Activate conda environment
        run: conda activate myenv
      - name: Install conda-smithy
        run: conda install -c conda-forge conda-smithy
      - name: Build conda package
        run: conda smithy rerender
      - name: Upload to conda-forge
        uses: conda-incubator/conda-forge-upload-action@v2
        with:
          package_glob: /home/runner/work/tpot2/tpot2/dist/*.tar.bz2
          secrets: CONDA_API_TOKEN
